### ISSUE TITLE
straight lines issue

### ISSUE THREAD

**Issue by gcmartijn** [mourner/simplify-js#15]
I convert your code to a language I'm using.
But it's not possible to get only the 'important' points if needed.

Maybe I can't use your code, maybe I can, I don't know.

Look at this image: http://s16.postimg.org/afccosymd/test_col.png
I have the exact outline coordinate's, what I need is only the corners (in this case)
So 16 x,y points.

When I set the tolerance using your script very high, it will create gaps inside the corners...

**Comment by mourner** [comment]
Please be more specific. What did you expect, and what do you get instead? Can you set up a test case with exact coordinates and tolerance values used?

**Comment by gcmartijn** [comment]
Here you go: http://s3.postimg.org/67v1cbezn/example.png

As you can see, I thought it would respect the corner points, and give me only the corners with a very high tolerance.

**Comment by mourner** [comment]
That's pretty weird, shouldn't work this way. I'll check this out.

**Comment by gcmartijn** [comment]
mmm maybe its my code then, check this later
Op 26 mei 2015 16:06 schreef "Vladimir Agafonkin" <notifications@github.com

**Comment by mourner** [comment]
@gcmartijn yeah, looking at the picture, it looks like it shows everything except the points that simplify.js retained.

**Comment by gcmartijn** [comment]
I'm now using your code directly to check where the problem is.
https://jsfiddle.net/5e2bot1r/1/

If you run it, you can see the wrong dots.

**Comment by mourner** [comment]
@gcmartijn hmm, your fiddle doesn't show anything for me in Chrome, just a blank screen.

**Comment by mourner** [comment]
@gcmartijn nevermind, seeing the points. If you run it with proper tolerance (say 1), the result is good — just the important corners.

**Comment by gcmartijn** [comment]
I'm using the latest chrome, don't you see the red pixel (right side) when when push Run?
http://s16.postimg.org/5f3vqacnp/Screen_Shot_2015_05_31_at_13_05_07.png

**Comment by gcmartijn** [comment]
I see now, maybe its the python module, going to recheck that again.
