### ISSUE TITLE
Are there any plans for Catmull-Rom smoothing?

### ISSUE THREAD

**Issue by nicholaswmin** [mourner/simplify-js#16]
I'm using the lib in a project I'm on:

It works flawlessly and is pretty fast(which is critical, I'm working with very tight performance tolerances)
I'm using it to simplify a pencil line that a user can draw on a canvas. Having less points makes it ideal for real-time collaboration since there's not too much data to transmit between each client for each path.

However, I'd love if there was also *smoothing available* through the lib. 
Most of the smoothing algorithms won't really work since they are distorting the original path.

However *Centripetal Catmull–Rom smoothing* can actually work since it:

- Does not self-intersect on tight corners
- Fits much more snug on the points given

Are there any plans to allow such sort of smoothing through Simplify.js?

=====

An image for comparing between the different Catmull-Rom interpolations:

![image](https://cloud.githubusercontent.com/assets/3926463/7994924/26199e48-0b1a-11e5-93c5-56eba748e012.png)

**Comment by mourner** [comment]
No plans to support smoothing because this has very specific use cases and should really be a separate library. Thanks for the nice explanation though.
