### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bborowin** [mourner/simplify-js#23]
When operating on large data sets (array of 20K+ {x,y} objects), the library throws the stack size exceeded exception.

```
angular.js:13708 RangeError: Maximum call stack size exceeded
    at simplifyDPStep (simplify.js:71)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
    at simplifyDPStep (simplify.js:85)
```

**Comment by mourner** [comment]
This is weird. Can you set up a JSFiddle that reproduces the issue?

**Comment by mourner** [comment]
Closed because of no response.

**Comment by quadrateer** [comment]
`    it('should work with a malicious input', () => {`
`      const rectangle = [`
`        [15.013, 49.144],`
`        [15.013, 49.154],`
`        [15.003, 49.154],`
`        [15.003, 49.144],`
`      ];`

`      const coordinates: Coordinates[] = [];`
`      for (let i = 0; i < 5000; i++) {`
`        coordinates.push(new Coordinates(rectangle[0][0], rectangle[0][1]));`
`        coordinates.push(new Coordinates(rectangle[1][0], rectangle[1][1]));`
`        coordinates.push(new Coordinates(rectangle[2][0], rectangle[2][1]));`
`        coordinates.push(new Coordinates(rectangle[3][0], rectangle[3][1]));`
`      }`

`      const result = service.simplify(coordinates, 0.0005, false);`
`      expect(result.length).toBe(coordinates.length);`
`    });`

Not exactly a JSFiddle, and not exactly simplify structure, but that would be it ;)
