### ISSUE TITLE
Unable to return complex polygon shapes without coordinate 'inflation'

### ISSUE THREAD

**Issue by gregrowles** [mourner/simplify-js#25]
I've noticed a small bug in the simplify() function. I've had trouble with the resulting coordinates almost always being 4-7 length polygons. The answer is to inflate the coordinates before and after, e.g. by a factor of 1000. Only once these values pass through the function are the results useful...

**Comment by mourner** [comment]
I'm not sure what you mean by this. Did you adjust the tolerance value?

**Comment by gregrowles** [comment]
Sorry, will upload clearer example next week

**Comment by gregrowles** [comment]
While looping through polygon coordinates (down to 14/15 decimals) I had
trouble returning simplified coordinates (only when i multiplied coords by
1000 did it return acceptable values). I think you've closed it correctly
so - now that i'm retesting i cannot replicate the error. Sorry to waste
time...
