### ISSUE TITLE
geojson

### ISSUE THREAD

**Issue by mikila85** [mourner/simplify-js#26]
hi, is there a way to simplify geoJSON with this awesome algorithm??

**Comment by mourner** [comment]
Use https://github.com/maxogden/simplify-geojson instead.

**Comment by mikila85** [comment]
@mourner i loved the "highest quality" option at your code :( too bad. thx anyway

**Comment by mourner** [comment]
@mikila85 you can use this code, but you'll have to convert the `[x, y]` GeoJSON point format to `{x: x, y: y}` format this module uses for points.
