### ISSUE TITLE
Undefined in results for empty and singleton arrays

### ISSUE THREAD

**Issue by dphilipson** [mourner/simplify-js#28]
`simplify([])` returns `[undefined]`, and `simplify([{x: 0, y: 0}])` returns `[{x: 0, y: 0}, undefined]`. I would expect these to return `[]` and `[{x: 0, y: 0}]` respectively.

**Comment by dphilipson** [comment]
Apologies. This is fixed in the latest version.

**Comment by AlexWayfer** [comment]
@mourner, can you publish the new version with this fix in `npm`, please?

**Comment by mourner** [comment]
Oops, don't know how I overlooked that. Published.

**Comment by AlexWayfer** [comment]
Thank you! :heart:
