### ISSUE TITLE
How to utilize with stroke data including pressure/z-axis data?

### ISSUE THREAD

**Issue by evitolins** [mourner/simplify-js#29]
Love this great little utility.

I'm working with a sketch application that receives pressure data, and applies it to the resulting stroke (width and/or density...etc).  I suppose it could considered x, y & z axis data.

I'd love to simplify the curves from the user's raw input, but I need to reapply the pressure data, along with the point locations for the idealized curve.

Do you have any suggestions how that could be done with simplify-js?  Any help would be appreciated. :)

**Comment by evitolins** [comment]
If the idealized curve contains only points from the original curve, all I'd really need is a list of all the used indices from the original curve.  With that, I could reference the original curve and retrieve the point's extra data after the fact.

**Comment by evitolins** [comment]
:/  I've just realized you have a 3D branch... hold that thought for a moment

**Comment by mourner** [comment]
Actually you should be able to use simplify-js as is, because it simply copies point objects from the original array into a new one, so if you have custom attributes on them (such as original indices or pressure values), they'll be preserved.

**Comment by evitolins** [comment]
Thanks of your quick reply!  I'll dig in and see what I can do :).
