### ISSUE TITLE
Please Add Simplification Of Curves

### ISSUE THREAD

**Issue by anonyco** [mourner/simplify-js#35]
Would it be possible to add simplification for [curves](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Cubic_B%C3%A9zier_Curve)? Simplification for curves would be an unbelievable asset and would draw so much more attention to this library.

**Comment by mourner** [comment]
Unfortunately there are no plans to do that. I think this would be a good candidate for a separate library.
