### ISSUE TITLE
Getting only 2 results back

### ISSUE THREAD

**Issue by jimmykane** [mourner/simplify-js#37]
Hi I am using the latest version of this lib but I am having issues

My input data are lat,long and I do convert them to x,y

```
 const b = positions.map((position) => {
            return {x: position.latitudeDegrees , y: position.longitudeDegrees}

          });
```

<img width="259" alt="Screenshot 2019-07-22 at 12 50 10" src="https://user-images.githubusercontent.com/1268723/61627115-4a5ddc00-ac7f-11e9-81de-8c81b31d3060.png">

Then 

```
          const a  = simplify(b, 0.1, true);

```

<img width="239" alt="Screenshot 2019-07-22 at 12 50 20" src="https://user-images.githubusercontent.com/1268723/61627126-4f229000-ac7f-11e9-9c4e-b3bebabde819.png">

However the result only has a 2 item array. 

(also the lib is not published related to latest master)

**Comment by mourner** [comment]
This is because your tolerance is too high. Try something like 0.00001.

**Comment by atomkirk** [comment]
simply doesn't work on arrays that are too small it seems 
![image](https://user-images.githubusercontent.com/2091439/82462149-73562580-9a78-11ea-8feb-c65f1ae0ee60.png)
