### ISSUE TITLE
Version on NPM is not version in GitHub

### ISSUE THREAD

**Issue by RobertDoc** [mourner/simplify-js#38]
When adding this package to a project via
```
    "simplify-js": "latest",
```

It does not have the TypeScript definition file.

**Comment by pbock** [comment]
It looks like the type definitions were added after v1.2.3 was published. Bumping the version number to 1.2.4 and re-publishing on npm should do the trick.

**Comment by RobertDoc** [comment]
Hi, any update on this is this possible?

**Comment by Marujah** [comment]
Hi,
any updates?

**Comment by mourner** [comment]
@Marujah v1.2.4 is the latest version (including types) and it's on NPM.
