### ISSUE TITLE
Does it support self-intersecting paths?

### ISSUE THREAD

**Issue by maxsmadt** [mourner/simplify-js#42]
Hi,

Would like to see if the library supports self-intersecting paths?

**Comment by mourner** [comment]
Yes, this doesn't affect simplifcation in any way.

**Comment by maxsmadt** [comment]
thank you @mourner

**Comment by ngrhadi** [comment]
what this feature also same like d3-geopath for intersection on every path like when draw multiLineString to intersect with existing point?
