### ISSUE TITLE
Feature Request: time component

### ISSUE THREAD

**Issue by theprojectsomething** [mourner/simplify-js#43]
Is there a simple way to consider / include time series data (or an arbitrary extra component/unit) or is this better left to post processing? E.g something that could solve for the following:

```js
// a simple track
const timed = [
  { x: 0, y: 0, t: 0},
  { x: 0, y: 1, t: 1}, // speed == 1/t
  { x: 0, y: 1, t: 2}, // speed == 0
  { x: 1, y: 0, t: 3}, // speed == 1
];

simplify(timed, 0.5);
/*
[
  { x: 0, y: 0, t: 0},
  { x: 0, y: 1, t: 1}, // speed == 1
  { x: 1, y: 0, t: 3}, // speed == 0.5
];
*/
```

**Comment by mourner** [comment]
The algorithm is purely geometric and only considers the `x` and `y` coordinates, although it will still work as above (filtering out the duplicate point).

**Comment by theprojectsomething** [comment]
No worries - thanks for quick response; yes, above was the expected output from a purely geometric output (which shows losing the time context). Would you consider merging a branch for a time dimension (4D), similar to the 3D branch? Specifically for gps tracks.

**Comment by theprojectsomething** [comment]
FYI - I was able to get a suitable result by running a second simplification on a speed vs time curve and combining with the position curve. The idea is not to lose speed variations on straight line geometries.

@mourner I notice your github pages example doesn't use `lng, lat` ... but in some issue responses you suggest mapping `{ x: lng, y: lat }`. Would you expect any significant effect on curves spanning that much `lat` given non-linear `lng` distance?

**Comment by mourner** [comment]
@theprojectsomething yeah, it may be a little skewed if you run it on the raw lng/lat coordinates, however you can mostly fix this (at least on city-level data) by scaling `y` values by `Math.cos(lat * Math.PI / 180)` prior to simplification (and then scaling back the output), where `lat` is the general latitude of the input (e.g. the first point).
